CREATE DATABASE escola;
CREATE TABLE alunos;
CREATE TABLE professores;
CREATE TABLE turmas;
CREATE TABLE cursos;
CREATE TABLE matriculas;
CREATE TABLE notas;
CREATE TABLE usuarios;
CREATE TABLE presenca;
CREATE TABLE funcionarios;
CREATE TABLE advertencias
